# Site settings
title: Eli Sander
smalltalk: "Tech Lead + Data Scientist"
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "" # the base hostname & protocol for your site
github_username: elsander
linkedin_url: "https://www.linkedin.com/profile/view?id=AAMAAApzv2UBPiQAV9frxat_NUWqBSDL0LnLgGQ&trk=hp-identity-name"
portfolio_url: 

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
